name: Compile example paper

on:
  # Build any branch
  push:
    paths:
      - 'example/*'
  pull_request:
    paths:
      - 'example/*'
    # Build, but don't push on pull requests

jobs:
  build:
    name: Example PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build PDF
        run: >-
          docker run \
              --volume "$(pwd):/data" \
              --user "$(id -u):$(id -g)" \
              openjournals/inara:latest \
              -o neurolibre example/paper.md

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: example/paper.pdf
